spring:
  profiles:
    active:
     -dev
---
server:
  port: 12001
mybatis:
  # mybatis 配置文件存放位置
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 我们的实体类的存放位置
  type-aliases-package: com.xiaobaibi.bean
  # ORM 映射文件
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
#  微服务名称(重复)
    name: msc-department
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.93.155:3306/xiaobaibi01
    username: root
    password: root
    dbcp2:
#    最少连接数据
      min-idle: 5
#    初始化连接数
      initial-size: 5
#    最大连接数
      max-total: 5
#    超时时间
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
#   在 Eureka 页面中显示的URL名称
    instance-id: msc-department-12001
#   在 Eureka 页面中显示的URL名称中是否以真实LocalIP显示
    prefer-ip-address: true
# 将本服务注册到Eureka Server中

info:
  app.name: msc-api-department-12001
  company.name: www.xiaobaibi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 12001
mybatis:
  # mybatis 配置文件存放位置
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 我们的实体类的存放位置
  type-aliases-package: com.xiaobaibi.bean
  # ORM 映射文件
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
#  微服务名称(重复)
    name: msc-department
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.93.155:3306/xiaobaibi02
    username: root
    password: root
    dbcp2:
#    最少连接数据
      min-idle: 5
#    初始化连接数
      initial-size: 5
#    最大连接数
      max-total: 5
#    超时时间
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
#   在 Eureka 页面中显示的URL名称
    instance-id: msc-department-12001
#   在 Eureka 页面中显示的URL名称中是否以真实LocalIP显示
    prefer-ip-address: true
# 将本服务注册到Eureka Server中

info:
  app.name: msc-api-department-12001
  company.name: www.xiaobaibi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$