spring:
 profiles:
  active:
   -dev
---
server:
 port: 8101
spring:
 profiles: dev
 application:
  name: msc-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-dev.com:7001/eureka/
---
server:
 port: 8102
spring:
 profiles: test
 application:
  name: msc-config-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-test.com:7001/eureka/